# Copyright 2020 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1463
# https://docs.mirantis.com/docker-enterprise/v3.1/dockeree-products/docker-engine-enterprise/dee-windows.html#install-script-usage
# Requires license. If you running on Azure License is currently provided with Windows Server images.
- name: Download Docker EE installer
  win_get_url:
    url: https://get.mirantis.com/install.ps1
    dest: '%TEMP%\install.ps1'
  register: docker

- name: Install Docker EE
  win_shell: "{{ docker.dest }}"

- name: Set up Docker Network
  win_shell: |
    $exists=docker network ls -f name=host -q
    if (-not $exists) { docker network create -d nat host }

- name: Pre-pull images
  win_command: docker pull {{ item }}
  loop: "{{ prepull_images }}"
  when: prepull

- name: Pre-pull additional images
  win_command: docker pull {{ item }}
  loop: "{{ additional_prepull_images_list }}"
  when: additional_prepull_images_list|length > 0
  